### ISSUE TITLE
A user can view the project name.

### ISSUE THREAD

**Issue by thebearingedge** [alexkim-is/repo_1#5]
- [x] Browse pages 1 - 58 of Duckett's HTML & CSS.
- [x] Create a webpage with a `html`, `body`, `title`, and `h1` tags.

Check out [mdn](https://developer.mozilla.org/en-US/) for the authoritative documentation.

**Comment by alexkim-is** [comment]
<!DOCTYPE html>
  <html lang="en-us">
    <head>
      <title> Alex's Homepage </title>
    </head>
    <body>
      <h1> Welcome to my page </h1>
    </body>
  </html>

**Comment by thebearingedge** [comment]
Hi Alex, your webpage should be an index.html added to a new branch of your repository.

**Comment by alexkim-is** [comment]
Thanks Tim.  I created a new pull request regarding index.html file.
